%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 					Dockerfile:Router
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
###### Referencias Dockerfile
# FRR Alpine
https://hub.docker.com/r/frrouting/frr/dockerfile

# FRR Github
https://github.com/FRRouting/frr/tree/master/alpine
https://github.com/FRRouting/frr/blob/master/docker/alpine/Dockerfile
# FRR Alpine
https://aurora.nox.tf/tmp/frr-doc/dev/building-frr-for-alpine.html
# FRR Alpine Edge
https://www.uni-koeln.de/~pbogusze/posts/Building_64bit_alpine_linux_GNS3_FRRouting_appliance.html
# FRR Ubuntu
https://github.com/ksator/frrouting_demo/blob/master/Dockerfile
# FRR Alpine
https://fossies.org/linux/frr/docker/alpine/build.sh

############################  Errores ############################

############################ Documentación FRR############################

# Configuraciones:
https://www.youtube.com/watch?v=y1ikVKvWXpQ&ab_channel=TechUpskill
https://docs.frrouting.org/en/latest/setup.html
https://www.eduardocollado.com/2019/06/28/frrouting/
https://wiki.gentoo.org/wiki/Frr#Installation
https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-41/Layer-3/Configuring-FRRouting/


############################### Comandos ###############################




