%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
						Dockerfile: FTP
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## DockerFile
#  DockerFile DHCP, DNS, FTP, HTTP
https://karneliuk.com/2019/04/building-zero-touch-provisioning-infrastructur-dhcp-dns-ftp-http-with-netbox-docker-and-ansible-for-arista-eos-cumulus-linux-cisco-ios-xr-and-nokia-sr-os/

# VSFTPD ALPINE
https://www.hiroom2.com/2017/08/22/alpinelinux-3-6-vsftpd-en/
https://wiki.alpinelinux.org/wiki/FTP
# VSFTPD ALPINE
https://gitlab.com/the-foundation/docker-vsftpd-sftp-s3
# VSFTPD CENTOS 7 
https://gitlab.cern.ch/fts/ready-to-go/-/tree/master/ftp

################################### Comando ###################################
docker run --privileged=true -dti -v /home/pi/Desktop/Andres-TIC2023/Docker\ DockerFile/FTP/FTP/vsftpd_active_local.conf:/etc/vsftpd/vsftpd.conf --net host --name serverftp andresye/vsftpd
Nota: CONFIGURAR DIRECCIONES IP EN ARCHIVOS  .conf !!!!!!!

################################### Errores ###################################
Nota: Problemas 500 
https://community.rsa.com/t5/securid-governance-lifecycle/winscp-or-ftp-from-the-command-line-prompt-fails-with-oops-child/ta-p/862
https://itecnotes.com/server/linux-vsftp-error-500-oops-child-died/
https://ubuntuforums.org/showthread.php?t=2273364
#################################### Documentación FTP ####################################

https://blog.irontec.com/voip-y-la-guerra-por-el-crecimiento-horizontal-con-el-trio-docker-kamailio-y-asterisk/

Passive Mode
https://blog.ahierro.es/ftp-activo-vs-ftp-pasivo/ 
https://blog.infranetworking.com/puerto-ftp/#FTP 
https://mac.eltima.com/es/ftp-port.html


Servidores Virtuales:
https://blog.ahierro.es/usuarios-virtuales-en-vsftp/
PAM:
-https://blog.ahierro.es/usuarios-virtuales-en-vsftp/
-https://blogsaverroes.juntadeandalucia.es/plataformaeiv/files/2016/05/P-vsftpd-autenticacion.pdf
-https://github.com/epoweripione/docker-vsftpd-alpine/blob/master/Dockerfile
